name: upload website to S3

on:
  push:
    #branches:
    #  - main  

jobs:
  upload-to-s3:
    name: Upload to S3
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      # Step 3: Upload folder to S3
      - name: Upload folder to S3
        run: |
          aws s3 sync ./CherryBlossom s3://${{ secrets.AWS_BUCKET_NAME }}/
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
