name: Upload/Update Website Front to S3

on:
  workflow_dispatch:
  push:
    branches:
      - main  
    paths:
      - 'CherryBlossom/**'  # Run only if files in this folder change

jobs:

  restricted_job:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if not on main branch
        if: github.ref != 'refs/heads/main'
        run: |
          echo "This workflow can only be triggered from the main branch."
          exit 1

  upload-to-s3:
    name: Upload to S3
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  
          
      # Step 3: Upload folder to S3
      - name: Upload folder to S3
        run: |
          aws s3 sync ./CherryBlossom s3://${{ vars.S3_BUCKET_NAME }}

      # Step 4: Invalidate CloudFront Cache for changed HTML files
      - name: Invalidate CloudFront Cache for index.html
        env:
          BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
        run: |
          DISTRIBUTION_IDS=$(aws cloudfront list-distributions \
            --query "DistributionList.Items[?Origins.Items[?contains(DomainName, '${BUCKET_NAME}.s3.amazonaws.com')]].Id" \
            --output text)

          if [ -z "$DISTRIBUTION_IDS" ]; then
            echo "No CloudFront distribution found for bucket: $BUCKET_NAME"
            exit 0  # Exit gracefully without failing the workflow
          fi

          for DISTRIBUTION_ID in $DISTRIBUTION_IDS; do
            echo "Invalidating CloudFront distribution: $DISTRIBUTION_ID"
            aws cloudfront create-invalidation \
              --distribution-id "$DISTRIBUTION_ID" \
              --paths "/*"
          done
