name: Terraform plan

on:
  #push:
    #branches:
    #  - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'infra/**'  # Run only if files in this folder change
      - '.github/workflows/infra-preview.yml'

jobs:
  
  # restricted_job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Fail if not on main branch
  #       if: github.ref != 'refs/heads/main'
  #       run: |
  #         echo "This workflow can only be triggered from the main branch."
  #         exit 1
  
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Change to infra directory
        run: cd /home/runner/work/AWS-Resume-Challange/AWS-Resume-Challange/infra

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.0'

      - name: Terraform Init
        run: | 
          cd /home/runner/work/AWS-Resume-Challange/AWS-Resume-Challange/infra
          terraform init
        working-directory: ./infra

      - name: Terraform Plan
        run: | 
          cd /home/runner/work/AWS-Resume-Challange/AWS-Resume-Challange/infra
          terraform plan -out=tfplan
        env:
          TF_VAR_s3_bucket_name: ${{ vars.S3_BUCKET_NAME }}
          TF_VAR_alternate_domain_name: ${{ vars.ALTERNATE_DOMAIN_NAME }}
          TF_VAR_lambda_function_name: ${{ vars.LAMBDA_FUNCTION_NAME }}
          TF_VAR_dynamodb_table_name: ${{ vars.DYNAMO_DB_TABLE_NAME }}
        working-directory: ./infra

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: ./infra

    
