name: Terraform Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'  # Run only if files in this folder change
      - '.github/workflows/infra**'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.0'

      - name: Change to infra directory
        run: cd infra

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_s3_bucket_name: ${{ vars.S3_BUCKET_NAME }}
          TF_VAR_alternate_domain_name: ${{ vars.ALTERNATE_DOMAIN_NAME }}
          TF_VAR_lambda_function_name: ${{ vars.LAMBDA_FUNCTION_NAME }}
          TF_VAR_dynamodb_table_name: ${{ vars.DYNAMO_DB_TABLE_NAME }}
        

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   env:
      #     TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     TF_VAR_s3_bucket_name: ${{ vars.S3_BUCKET_NAME }}
      #     TF_VAR_alternate_domain_name: ${{ vars.ALTERNATE_DOMAIN_NAME  }}
      #     TF_VAR_lambda_function_name: ${{ vars.LAMBDA_FUNCTION_NAME }}
      #     TF_VAR_dynamodb_table_name: ${{ vars.DYNAMO_DB_TABLE_NAME }}
